// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sedfajfvgwbtldqvxqqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlZGZhamZ2Z3didGxkcXZ4cXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDk2NjQsImV4cCI6MjA2NDYyNTY2NH0.pOn1NjRbh7dqLAc-AxjGF3yI_FYeyELnfH3aVrcHh3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);